export const centres = [
  {
    name: "CENTRE FOR EDUCATION, HEALTH, PSYCHOLOGY, COUNSELLING & HUMAN SERVICES",
    categories: [
      {
        name: "Education",
        programmes: [
          "Professional Certificate in Modern Teaching Methods and Classroom Management",
          "Professional Certificate in Digital Teaching and Learning Technologies",
          "Professional Certificate in Educational Leadership and School Administration",
          "Professional Certificate in Curriculum Development and Instructional Design",
          "Professional Certificate in Assessment, Examination and Educational Evaluation",
          "Professional Certificate in Special Education and Inclusive Learning",
          "Professional Certificate in Early Childhood Education and Child Development",
          "Professional Certificate in Teaching English as a Second Language",
          "Professional Certificate in School Guidance, Mentoring and Student Support",
          "Professional Certificate in Education Administration and Quality Assurance",
        ],
      },
      {
        name: "Community Health, Public Health & Wellness",
        programmes: [
          "Professional Certificate in Community Health Promotion & Health Education",
          "Professional Certificate in Public Health, Disease Prevention & Community Outreach",
          "Professional Certificate in Nutrition, Wellness & Healthy Lifestyle Management",
          "Professional Certificate in Mental Health Awareness & Psychological First Aid",
          "Professional Certificate in Infection Prevention, Control & Hygiene",
          "Professional Certificate in Health Communication & Patient Relations",
          "Professional Certificate in First Aid, Basic Life Support & Emergency Response",
        ],
      },
      {
        name: "Healthcare Administration",
        programmes: [
          "Professional Certificate in Health Administration & Healthcare Management",
          "Professional Certificate in Health Records & Medical Information Management",
          "Professional Certificate in Healthcare Administration, Customer Service & Patient Relations",
        ],
      },
      {
        name: "Home Care & Caregiving",
        programmes: [
          "Professional Certificate in Home Care & Professional Caregiving",
          "Professional Certificate in Elderly Care & Ageing Support",
          "Professional Certificate in Disability Support & Community Care",
          "Professional Certificate in Childcare & Family Support",
          "Professional Certificate in Personal Care Assistance & Daily Living Support",
          "Professional Certificate in Home Care Services & Caregiving",
          "Professional Certificate in Elderly Care, Disability Support & Community-Based Care",
        ],
      },
      {
        name: "Psychology",
        programmes: [
          "Professional Certificate in Introduction to Psychology and Human Behaviour",
          "Professional Certificate in Child and Adolescent Psychology",
          "Professional Certificate in Workplace Psychology and Employee Wellbeing",
          "Professional Certificate in Psychology of Leadership and Management",
          "Professional Certificate in Stress Management and Emotional Wellbeing",
          "Professional Certificate in Behavioural Communication and Conflict Management",
          "Professional Certificate in Psychology for Education and Student Support",
          "Professional Certificate in Human Behaviour, Motivation and Personal Development",
          "Professional Certificate in Applied Psychology for Workplace and Community",
        ],
      },
      {
        name: "Counselling & Human Services",
        programmes: [
          "Professional Certificate in Basic Counselling Skills",
          "Professional Certificate in Youth Counselling and Mentorship",
          "Professional Certificate in School Counselling and Student Support",
          "Professional Certificate in Workplace Counselling and Employee Support",
          "Professional Certificate in Family Support and Conflict Resolution",
          "Professional Certificate in Addiction Awareness and Community Support",
          "Professional Certificate in Grief, Loss and Bereavement Support",
          "Professional Certificate in Stress, Emotional Wellness and Resilience",
          "Professional Certificate in Peer Counselling and Community Support",
          "Professional Certificate in Counselling Skills and Human Services",
        ],
      },
    ],
  },
  {
    name: "CENTRE FOR ADVANCED AI, DIGITAL TECHNOLOGY, MEDIA & COMMUNICATION",
    categories: [
      {
        name: "Artificial Intelligence & Digital Skills",
        programmes: [
          "Professional Certificate in Artificial Intelligence and Digital Fundraising",
          "Professional Certificate in AI for Business and Entrepreneurship",
          "Professional Certificate in AI-Assisted Academic Writing, Research & Scholarly Publishing",
          "Professional Certificate in AI for Academic Research, Data Analysis & Productivity",
          "Professional Certificate in AI-Powered Social Media Content Creation & Monetization",
          "Professional Certificate in AI for Workplace Productivity",
          "Professional Certificate in AI for Small Business and SME Development",
          "Professional Certificate in Generative AI Tools for Professionals",
          "Professional Certificate in AI Ethics, Governance & Responsible Use",
        ],
      },
      {
        name: "Web & Digital Technology",
        programmes: [
          "Professional Certificate in Web Design and Development",
          "Professional Certificate in WordPress Website Development",
          "Professional Certificate in Front-End Web Development",
          "Professional Certificate in Full-Stack Web Development",
          "Professional Certificate in E-Commerce Website Development",
          "Professional Certificate in UX/UI and Mobile-Friendly Web Design",
          "Professional Certificate in Website Management, Security & Maintenance",
          "Professional Certificate in No-Code and Low-Code Website Development",
        ],
      },
      {
        name: "Social Media & Digital Marketing",
        programmes: [
          "Professional Certificate in Social Media Content Creation & Digital Advertising",
          "Professional Certificate in Digital Marketing and Online Business",
          "Professional Certificate in Social Media Management",
          "Professional Certificate in Digital Branding and Personal Branding",
          "Professional Certificate in Digital Advertising and Campaign Management",
          "Professional Certificate in E-Commerce and Social Commerce",
          "Professional Certificate in Content Marketing and Digital Storytelling",
          "Professional Certificate in Digital Sales and Customer Acquisition",
        ],
      },
      {
        name: "Media, Broadcasting & Communication",
        programmes: [
          "Professional Certificate in Online Radio & Television Presentation, News & Sports Broadcasting",
          "Professional Certificate in Journalism and Digital News Reporting",
          "Professional Certificate in Mobile Journalism and Digital Reporting",
          "Professional Certificate in Professional Communication and Public Speaking",
          "Professional Certificate in Corporate Communication and Public Relations",
          "Professional Certificate in Strategic Communication and Media Relations",
          "Professional Certificate in Crisis Communication and Reputation Management",
          "Professional Certificate in Speech Writing and Professional Presentation",
        ],
      },
    ],
  },
  {
    name: "CENTRE FOR DEVELOPMENT, PROJECT MANAGEMENT, LAW, GOVERNANCE & LEADERSHIP STUDIES",
    categories: [
      {
        name: "Project Management",
        programmes: [
          "Professional Certificate in Project Management Fundamentals",
          "Professional Certificate in Project Planning, Implementation and Monitoring",
          "Professional Certificate in Project Monitoring, Evaluation and Learning (MEL)",
          "Professional Certificate in Project Risk Management",
          "Professional Certificate in Project Budgeting, Financial Management and Reporting",
          "Professional Certificate in NGO and Development Project Management",
          "Professional Certificate in Project Proposal Development and Grant Management",
          "Professional Certificate in Agile Project Management",
          "Professional Certificate in Procurement and Contract Management for Projects",
        ],
      },
      {
        name: "Development Studies & Economics",
        programmes: [
          "Professional Certificate in Development Studies and Social Development",
          "Professional Certificate in Development Economics and Economic Policy",
          "Professional Certificate in Economic Development and Poverty Reduction",
          "Professional Certificate in Public Finance and Economic Management",
          "Professional Certificate in Economic Data Analysis and Policy Research",
          "Professional Certificate in Sustainable Development and Economic Planning",
          "Professional Certificate in Socioeconomic Research and Impact Assessment",
          "Professional Certificate in Development Planning and Policy Analysis",
          "Professional Certificate in Economic Project Appraisal",
        ],
      },
      {
        name: "NGO & Nonprofit Management",
        programmes: [
          "Professional Certificate in NGO Management and Administration",
          "Professional Certificate in Nonprofit Leadership and Governance",
          "Professional Certificate in Community Development and Mobilization",
          "Professional Certificate in Humanitarian Programme Management",
          "Professional Certificate in Monitoring, Evaluation, Research and Learning",
          "Professional Certificate in Grant Proposal Writing and Fundraising",
          "Professional Certificate in Donor Relations and Development Finance",
          "Professional Certificate in Social Impact and Community Project Management",
        ],
      },
      {
        name: "Law, Governance & Compliance",
        programmes: [
          "Professional Certificate in Law and Legal Studies",
          "Professional Certificate in Human Rights and Social Justice",
          "Professional Certificate in Corporate Governance and Compliance",
          "Professional Certificate in Business Law for Entrepreneurs",
          "Professional Certificate in Labour Law and Workplace Relations",
          "Professional Certificate in Alternative Dispute Resolution",
          "Professional Certificate in Contract Management and Legal Compliance",
          "Professional Certificate in Data Protection, Privacy and Digital Law",
          "Professional Certificate in Anti-Corruption, Ethics and Institutional Integrity",
        ],
      },
      {
        name: "Politics & Public Leadership",
        programmes: [
          "Professional Certificate in Political Leadership and Governance",
          "Professional Certificate in Public Policy Analysis",
          "Professional Certificate in Election Management and Democratic Governance",
          "Professional Certificate in Political Campaign Strategy and Management",
          "Professional Certificate in Political Communication and Public Relations",
          "Professional Certificate in Public Opinion Research and Polling",
          "Professional Certificate in Legislative Processes and Parliamentary Affairs",
          "Professional Certificate in Local Government and Decentralization",
          "Professional Certificate in Leadership, Ethics and Public Accountability",
        ],
      },
    ],
  },
  {
    name: "CENTRE FOR FOOD & HOSPITALITY INDUSTRY MANAGEMENT",
    categories: [
      {
        name: "Culinary & Food Production",
        programmes: [
          "Professional Certificate in Culinary Arts & Food Preparation",
          "Professional Certificate in Ghanaian & African Cuisine Production",
          "Professional Certificate in Chinese, European & American Cuisine",
          "Professional Certificate in Professional Catering & Event Food Services",
          "Professional Certificate in Baking, Bread, Cake, Pastry & Pie Production",
          "Professional Certificate in Confectionery & Dessert Production",
          "Professional Certificate in Basic Food Processing & Preservation",
          "Professional Certificate in Mushroom Cultivation, Processing & Value Addition",
        ],
      },
      {
        name: "Food Safety & Processing",
        programmes: [
          "Professional Certificate in Food Hygiene, Sanitation & Safe Food Handling",
          "Professional Certificate in Fruit Juice Processing & Non-Alcoholic Beverage Production",
          "Professional Certificate in Meat Processing, Preservation & Packaging",
          "Professional Certificate in Dairy Processing & Milk Product Manufacturing",
          "Professional Certificate in Food Processing, Preservation & Packaging Technology",
          "Professional Certificate in African Food Processing & Commercialization",
          "Professional Certificate in Food Product Development & Commercialization",
          "Professional Certificate in HACCP, Food Safety & Hygiene Management",
          "Professional Certificate in Food Packaging, Labelling & Product Standards",
          "Professional Certificate in Food Inspection, Quality Control & Compliance",
        ],
      },
      {
        name: "Hospitality",
        programmes: [
          "Professional Certificate in Restaurant & Food Service Operations",
          "Professional Certificate in Hotel Operations & Hospitality Services",
          "Professional Certificate in Front Office Operations & Guest Relations",
          "Professional Certificate in Housekeeping & Accommodation Services",
          "Professional Certificate in Hospitality Customer Service & Guest Experience",
          "Professional Certificate in Travel Ticketing, Reservations & Booking Services",
        ],
      },
      {
        name: "Food Business",
        programmes: [
          "Professional Certificate in Food Business Entrepreneurship",
          "Professional Certificate in Food Marketing & Sales",
          "Professional Certificate in Commercial Food Production & Kitchen Management",
          "Professional Certificate in Bakery & Confectionery Business Management",
          "Professional Certificate in Restaurant Management & Operations",
          "Professional Certificate in Catering Business Management",
          "Professional Certificate in Food Entrepreneurship & Business Management",
          "Professional Certificate in Food Marketing, Branding & Sales Management",
          "Professional Certificate in Food Business Development & Commercialization",
        ],
      },
    ],
  },
  {
    name: "CENTRE FOR ADVANCED BUSINESS, ENTREPRENEURSHIP, FINANCE, TRADE & SUPPLY CHAIN STUDIES",
    categories: [
      {
        name: "Business & Entrepreneurship",
        programmes: [
          "Professional Certificate in Entrepreneurship and New Venture Creation",
          "Professional Certificate in Small Business Management",
          "Professional Certificate in Business Planning and Startup Development",
          "Professional Certificate in SME Management and Growth",
          "Professional Certificate in Business Administration",
          "Professional Certificate in Office Administration and Management",
          "Professional Certificate in Operations Management",
          "Professional Certificate in Strategic Management",
          "Professional Certificate in Business Leadership and Supervisory Management",
        ],
      },
      {
        name: "Business Analytics & Productivity",
        programmes: [
          "Professional Certificate in Business Analytics and Business Development",
          "Professional Certificate in Excel for Business and Data Management",
          "Professional Certificate in Business Process Improvement",
          "Professional Certificate in Business Report Writing and Documentation",
          "Professional Certificate in Records and Information Management",
          "Professional Certificate in Professional Workplace Skills",
        ],
      },
      {
        name: "Banking & Finance",
        programmes: [
          "Professional Certificate in Banking Operations and Customer Service",
          "Professional Certificate in Banking and Financial Services Management",
          "Professional Certificate in Credit Analysis and Loan Administration",
          "Professional Certificate in Financial Literacy and Personal Money Management",
          "Professional Certificate in SME Financial Management",
          "Professional Certificate in Accounting Fundamentals and Bookkeeping",
          "Professional Certificate in Financial Analysis and Business Decision-Making",
          "Professional Certificate in Digital Banking and FinTech",
          "Professional Certificate in Risk Management and Internal Controls",
          "Professional Certificate in Banking Operations, Credit & Financial Services",
        ],
      },
      {
        name: "International Trade- Import & Export",
        programmes: [
          "Professional Certificate in International Trade and Global Business",
          "Professional Certificate in Import and Export Management",
          "Professional Certificate in Export Documentation and Procedures",
          "Professional Certificate in Customs, Tariffs and Trade Compliance",
          "Professional Certificate in International Shipping and Freight Management",
          "Professional Certificate in AfCFTA and African Market Development",
          "Professional Certificate in Export Marketing and International Market Research",
          "Professional Certificate in International Trade Finance",
          "Professional Certificate in Cross-Border E-Commerce and Global Selling",
          "Professional Certificate in International Trade & Export Business Development",
        ],
      },
      {
        name: "Supply Chain & Logistics",
        programmes: [
          "Professional Certificate in Supply Chain Management",
          "Professional Certificate in Procurement and Purchasing Management",
          "Professional Certificate in Inventory and Warehouse Management",
          "Professional Certificate in Logistics and Transport Management",
          "Professional Certificate in Procurement Planning and Contract Administration",
          "Professional Certificate in Supply Chain Risk Management",
          "Professional Certificate in Strategic Sourcing and Supplier Management",
          "Professional Certificate in Inventory Control and Demand Forecasting",
          "Professional Certificate in Procurement Ethics, Compliance and Fraud Prevention",
          "Professional Certificate in Supply Chain and Logistics Management",
        ],
      },
    ],
  },
  {
    name: "CENTRE FOR APPLIED AGRICULTURE, AGRIBUSINESS, ENGINEERING & TECHNICAL SKILLS",
    categories: [
      {
        name: "Agribusiness",
        programmes: [
          "Professional Certificate in Agribusiness Management and Entrepreneurship",
          "Professional Certificate in Modern Farming Business and Farm Management",
          "Professional Certificate in Agricultural Value Chain Management",
          "Professional Certificate in Agrifood Processing and Value Addition",
          "Professional Certificate in Agricultural Marketing and Market Access",
          "Professional Certificate in Farm Accounting, Costing and Financial Management",
          "Professional Certificate in Agricultural Supply Chain and Logistics",
          "Professional Certificate in Agribusiness Export and International Markets",
          "Professional Certificate in Digital Agriculture and Smart Farming",
          "Professional Certificate in Agribusiness Investment and Enterprise Development",
        ],
      },
      {
        name: "Engineering & Construction",
        programmes: [
          "Professional Certificate in Engineering Project Management",
          "Professional Certificate in Construction Project Management",
          "Professional Certificate in Occupational Health and Safety for Construction and Engineering",
          "Professional Certificate in Building Maintenance and Facilities Management",
          "Professional Certificate in Electrical Installation Management and Safety",
          "Professional Certificate in Solar Energy Systems and Renewable Energy Management",
          "Professional Certificate in Engineering Drawing and Computer-Aided Design (CAD)",
          "Professional Certificate in Quality Control and Quality Assurance for Engineering Projects",
          "Professional Certificate in Construction Estimating, Costing and Quantity Measurement",
          "Professional Certificate in Facilities, Building and Asset Management",
        ],
      },
    ],
  },
];
